project:
  type: website

website:
  title: "assignment_5"
  navbar:
    left:
      - href: about.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true



