{
  "hash": "c0fbd41451f6cb402c96d43a1802d3eb",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"WDI Exploration\"\nauthor: \"Daolong Yang\"\ndate: \"2024-10-08\"\nformat: \n  revealjs:\n    theme: moon\n    slide-number: true\n    transition: fade\n    incremental: true\n---\n\n\n# WDI Dataset Presentation\n\n\n\n# Exploratory Data Analysis\n\n::: {#d2dd3166 .cell execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\ncount       203.000000\nmean      20345.707649\nstd       31308.942225\nmin         259.025031\n25%        2570.563284\n50%        7587.588173\n75%       25982.630050\nmax      240862.182448\nName: gdp_per_capita, dtype: float64\ncount    169.000000\nmean      12.493936\nstd       19.682433\nmin       -6.687321\n25%        5.518129\n50%        7.967574\n75%       11.665567\nmax      171.205491\nName: inflation_rate, dtype: float64\ncount    186.000000\nmean       7.268661\nstd        5.827726\nmin        0.130000\n25%        3.500750\n50%        5.537500\n75%        9.455250\nmax       37.852000\nName: unemployment_rate, dtype: float64\n```\n:::\n:::\n\n\n## Analysis\n#### GDP-Per-Capita\nThe average GDP per capita is $20,345.71, with a wide range from $259.03 to $240,862.18. The median is $7,587.59, showing significant variation across countries.\n#### Inflation Rate\nThe average inflation rate is 12.49%, ranging from -6.69% to 171.21%. The median rate is 7.97%, with high variability indicated by a large standard deviation.\n#### GDP-Growth-Rate\nThe average GDP growth rate is 4.37%, with values ranging from -28.76% to 63.44%. The median growth rate is 4.20%.\n\n## Data Plots\n### GDP-Per-Capita across Countries\n\n::: {#53f1cdd0 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](presentation_files/figure-revealjs/cell-4-output-1.png){width=949 height=670}\n:::\n:::\n\n\n### Unemployment Rate By Total Population\n\n::: {#fe1a65ce .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](presentation_files/figure-revealjs/cell-5-output-1.png){width=949 height=670}\n:::\n:::\n\n\n### Key Statistics\n\n::: {#995af558 .cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\n   Unemployment Rate  Mean Population  Max Population\n0              0.130        2695122.0       2695122.0\n1              0.247       16767842.0      16767842.0\n2              0.552       26207977.0      26207977.0\n3              0.909        2538894.0       2538894.0\n4              0.919       12889576.0      12889576.0\n   Life Expectancy  Mean GDP-Per-Capita  Max GDP-Per-Capita\n0           52.997           699.463254          699.463254\n1           53.036           992.857328          992.857328\n2           53.633          2162.633732         2162.633732\n3           54.477           427.058096          427.058096\n4           55.567                  NaN                 NaN\n```\n:::\n:::\n\n\n",
    "supporting": [
      "presentation_files"
    ],
    "filters": [],
    "includes": {}
  }
}